name: Publish NuGet

on:
  release:
    types: [published]

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup .NET
        uses: actions/setup-dotnet@v1

      - name: Build
        run: dotnet build --configuration Release

      - name: Pack
        run: dotnet pack Net.Bluewalk.MongoDbEntities/Net.Bluewalk.MongoDbEntities.csproj --output nuget-packages --configuration Release

      - name: Push
        run: dotnet nuget push **/*.nupkg --skip-duplicate -k ${{ secrets.NUGET_API_KEY }}